### ISSUE TITLE
Usar fonte presente na pasta fonts

### ISSUE THREAD

**Issue by andrericruz** [andrericruz/LaTeX#1]
Estive a pesquisar mas não consegui encontrar o código para utilizar a fonte que está dentro da pasta fonts. Vou continuar a tentar se conseguires ver isto agradeço também! :)
[https://pt.sharelatex.com/learn/XeLaTeX#!#Setting_fonts_for_different_LaTeX_elements](url)
[https://tex.stackexchange.com/questions/12565/load-fonts-that-are-in-a-fonts-directory](url)
[http://aty.sdsu.edu/bibliog/latex/fonts.html](url)
[https://tex.stackexchange.com/questions/25249/how-do-i-use-a-particular-font-for-a-small-section-of-text-in-my-document/25251](url)
Estes foram os links onde eu pesquisei. A distribuição de latex que estou a usar é o MacTex.

**Comment by Squarehard** [comment]
Qual é a font que queres por?

**Comment by andrericruz** [comment]
A que está dentro da pasta fonts
